name: Reset Rate Limits

on:
  schedule:
    - cron: '0 0 * * *' # Schedule the job to run every day at midnight UTC

jobs:
  periodic-job:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Make API Call
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d '{"secret": "${{ secrets.RESET_LIMIT_CODE }}" }' \
            https://michel-barakat.vercel.app/api/rateLimiter
